### ISSUE TITLE
Use OAuth2 for IMAP

### ISSUE THREAD

**Issue by LMarly** [ZoeyVid/parsedmarc-dockerized#70]
Hello,

In the config.ini, we use legacy oauth with clear credential to use IMAP.

Do you know if it's possible to use OAuth2 for the connection with IMAP ?

I would like to use something similare as this : 

```
[retriever]
type = SimpleIMAPSSLRetriever
server = outlook.office365.com
username = email@outlook.com
password_command = ("getmail-gmail-xoauth-tokens", "C/.../.json")
use_xoauth2 = true

[destination]
type = MDA_external
path = C/....
arguments = ("--url=https://redmine.yourdomain.org", "--key-file=C/..../ws-api-key.txt", "--certificate-bundle=C/.../cert.pem")
#type = Maildir
#path = ~/Maildir/
```
PS:this is just an example, not usre that it will work in our case with parsedmarc

Thank you

**Comment by Zoey2936** [comment]
you may find more here: https://domainaware.github.io/parsedmarc/usage.html#configuration-file
